### PR TITLE
Database hotfix

### PR DESCRIPTION
**Pull request by starkshaw**
Fix the numeric bugs.

### CODE REVIEW

**Comment by danielpaul** [comment]
@starkshaw could we use the `change_column` method instead of just dropping the column. If we were to drop the column should have the migration copy over the data from the old one to the new one.

**Comment by starkshaw** [comment]
So it's like `change_column :products, :quantity, :integer`?

I use `remove_column` because I saw previous migration files used it.

**Comment by danielpaul** [comment]
http://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/change_column

**Comment by starkshaw** [comment]
Changed.

**Comment by danielpaul** [comment]
@starkshaw Also listen to my little robot @houndci-bot's feedback pls :P ;)

**Comment by starkshaw** [comment]
It's auto added by Atom...

Plus your robot is annoying.

**Pull request merged**
