### PR TITLE
Email confirmations

### PR DESCRIPTION
**Pull request by IonatanSala**
Have setup all the email confirmations for the ones specified on trello. Some of the controllers needed for the mailers aren't done yet. For example buying a product is not done so the email cannot be sent yet but it is all there for when that feature is done it can be easily integrated. E.g ConfirmationMailer.<method-name>()

### CODE REVIEW

**Comment by danielpaul** [comment]
@IonatanSala why does this branch have so many changes and commits from features that are not part of this task?

**Comment by IonatanSala** [comment]
@danielpaul because whenever I push something up I pull from master to resolve any merge conflicts, and I think I because I've created a new branch from the previous branch I was on.

**Comment by danielpaul** [comment]
@IonatanSala Can't cherry pick your commits with all the noise. Should only need to rebase once you are fully done and also that with `merge` with the `--no-ff` flag so it's just syncing with `master` and not creating all the noise taking attention from what was actually done on this task/branch.  https://github.com/SprintFire/marketplace/wiki/Rebasing-from-master-branch

**Comment by danielpaul** [comment]
@IonatanSala you need to exclude `public/uploads` from Git. It has your file uploads.

**Comment by IonatanSala** [comment]
Yes but because we are working with new branches without the old ones them being pulled into master we get these issues like adding the public/uploads not being in .gitignore

**Pull request merged**
