### PR TITLE
Purchases API Testing

### PR DESCRIPTION
**Pull request by LevinGeorge**
@IonatanSala Can you have a look at this please? 

error

### CODE REVIEW

**Comment by IonatanSala** [comment]
@LevinGeorge You need to have money in the shop to be able to widthdraw money. So make sure the shop that you are making a withdrawal from has a positive balance. So create a shop with some cash in it then try and make a withdrawal from it.

**Comment by LevinGeorge** [comment]
@IonatanSala Ehm there are 2 branches I'm stuck on. This and the withdrawal branch. I think the above comment was for withdrawal branch?

**Comment by LevinGeorge** [comment]
@starkshaw Ready to be merged as well.

**Comment by starkshaw** [comment]
@LevinGeorge Are they passed?

**Pull request merged**
