### PR TITLE
Styling right dashboard header

### PR DESCRIPTION
**Pull request by LevinGeorge**

### CODE REVIEW

**Comment by LevinGeorge** [comment]
@danielpaul This PR seems to be working right?

**Comment by danielpaul** [comment]
@LevinGeorge Yup :+1:

**Comment by danielpaul** [comment]
@LevinGeorge Is this ready to be merged?

**Comment by LevinGeorge** [comment]
@danielpaul Not yet. One more small thing to do. I will let you know soon

**Comment by danielpaul** [comment]
@LevinGeorge Cool. Assign it to me and tag as `code review` when ready.

**Comment by danielpaul** [comment]
@LevinGeorge Is this ready?

**Comment by starkshaw** [comment]
@danielpaul Finished, please review.

**Comment by starkshaw** [comment]
Can you merge this to ui?

**Pull request merged**
