### PR TITLE
Allow user to upload images

### PR DESCRIPTION
**Pull request by IonatanSala**
Give the user the ability to add a header and profile image for their shop.

### CODE REVIEW

**Comment by danielpaul** [comment]
@IonatanSala my little robot has a lot of comments for you :P

**Comment by danielpaul** [comment]
Tabs settings are 4 spaces I believe.

**Comment by IonatanSala** [comment]
Yeh but your little robot is repeating himself :P, and what's wrong with tabs in indentations that what you are supposed to use which is 2 spaces.

**Comment by danielpaul** [comment]
@IonatanSala The comments are the same comments but for different lines on your code :P Yes should probably be two spaces. Just make sure whatever the setting is we standardize your code to be that please.

**Pull request merged**
