### PR TITLE
Search Controller Unit Testing

### PR DESCRIPTION
**Pull request by starkshaw**

### CODE REVIEW

**Comment by danielpaul** [comment]
@starkshaw could we organise this into contexts?

**Comment by starkshaw** [comment]
@danielpaul I suggest you check again.

**Comment by danielpaul** [comment]
@starkshaw there are two contexts with logged in and logged out user. then a whole lot of tests inside. What I mean is context even more so a context for user not logged in but in that context for valid data and invalid data, then in that you could have contexts for testing categories, text, location separately and combination.

**Comment by starkshaw** [comment]
@danielpaul I think the `it` statements described them quite well in terms of "testing categories, text, location separately and combination". And there's not a neat way to classify them.

**Comment by starkshaw** [comment]
@danielpaul Finished.

**Pull request merged**
