### PR TITLE
User can edit their account

### PR DESCRIPTION
**Pull request by IonatanSala**
When the user logs in there is a Profile link on the navbar beside the logout link. When the user click this it will be brought to the users profile where they can edit their account.

### CODE REVIEW

**Comment by danielpaul** [comment]
@IonatanSala Can't edit the profile.
- [ ] Should update my details.
- [ ] User can change email and password (optional) but only these require current password to update.
- [ ] Design should be similar to the logged in app as opposed to the registration page. (Use default application layout)

**Comment by IonatanSala** [comment]
So you want to edit just the first and last name @danielpaul

**Comment by danielpaul** [comment]
@IonatanSala Currently yes, but also their existing email (which will then send a confirmation email to confirm again - all built into devise) and they can update their current password but only required current password for changing password and changing email address.

**Comment by IonatanSala** [comment]
So do you want me to use JavaScript for doing this or use logic in rails controllers?

**Comment by danielpaul** [comment]
@IonatanSala Why javascript? For which part?

**Comment by IonatanSala** [comment]
Never mind I understood it differently. It should work fine now.

**Comment by danielpaul** [comment]
@IonatanSala All logic and things should be prebuilt from devise for it already. You just need to set the view for it correctly. Checkout this app https://lifebites.herokuapp.com/ and look at the accounts editing page where you can update your account details.

**Comment by IonatanSala** [comment]
@danielpaul  No what I thought you meant was to show the current password only when the user is editing his email as in the User interface side of things. That's why I was asking about JS.

**Comment by danielpaul** [comment]
@IonatanSala Aha, well that's a great UX idea too. You can add that in too if you'd like :P :santa:

**Comment by IonatanSala** [comment]
@danielpaul Later on if we have time :stuck_out_tongue_winking_eye:

**Comment by danielpaul** [comment]
@IonatanSala Assign this back to me when you are finished and want me to review. Use labels too.

**Pull request merged**
