### PR TITLE
Fix Dashboard Authentication.

### PR DESCRIPTION
**Pull request by starkshaw**

### CODE REVIEW

**Comment by starkshaw** [comment]
Behold, there's a bug.

**Comment by danielpaul** [comment]
Thanks @starkshaw

**Comment by starkshaw** [comment]
There's a bug I told you... Can you revert?

**Comment by danielpaul** [comment]
aha, I thought you had already fixed that in this pull request @starkshaw

**Comment by starkshaw** [comment]
OK Fixed. Please merge.

**Comment by danielpaul** [comment]
@starkshaw Did you push up any new code? It's already merged otherwise.

**Comment by starkshaw** [comment]
Yes I did...

**Comment by danielpaul** [comment]
@starkshaw okey, so it's merged. Just confirm that all your changes have been merged: https://github.com/SprintFire/marketplace/pull/54/files

**Pull request merged**
